### ISSUE TITLE
加个readme.md吧

### ISSUE THREAD

**Issue by ugksoft** [irelance/jsc-decompile-mozjs-34#1]
加个readme.md吧,写一下需要环境之类, 不然看了php才知道需要7.0

**Comment by knagaitsev** [comment]
I am also wondering how to use this script. I am not sure if I have the correct php version, dependencies, and .jsc file to decompile. A readme.md is necessary.

**Comment by irelance** [comment]
already add

At 2018-02-11 00:30:02, "Loonride" <notifications@github.com> wrote:


I am also wondering how to use this script. I am not sure if I have the correct php version, dependencies, and .jsc file to decompile. A readme.md is necessary.
